// <auto-generated />
using System;
using EzDeal.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EzDeal.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EzDeal.Domain.Anuncio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnuncianteId");

                    b.Property<int>("Costo_Servicio");

                    b.Property<string>("Descripcion");

                    b.Property<string>("Dia");

                    b.Property<bool>("Esta_Habilitado");

                    b.Property<string>("HoraFin");

                    b.Property<string>("HoraInicio");

                    b.Property<int?>("ServicioId");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnName("titulo")
                        .HasMaxLength(50);

                    b.Property<float>("Valoracion");

                    b.HasKey("Id");

                    b.HasIndex("AnuncianteId");

                    b.HasIndex("ServicioId");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("EzDeal.Domain.Reseña", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnuncioId");

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Contenido");

                    b.Property<float>("Valoracion");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Reseñas");
                });

            modelBuilder.Entity("EzDeal.Domain.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("EzDeal.Domain.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AnuncioId");

                    b.Property<string>("Aprobacion");

                    b.Property<int?>("ClienteId");

                    b.Property<string>("Estado");

                    b.Property<string>("Mensaje");

                    b.HasKey("Id");

                    b.HasIndex("AnuncioId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("EzDeal.Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Contraseña");

                    b.Property<string>("Distrito");

                    b.Property<string>("Email");

                    b.Property<string>("Nombre");

                    b.Property<string>("Telefono");

                    b.Property<string>("Url_Contacto");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EzDeal.Domain.Anuncio", b =>
                {
                    b.HasOne("EzDeal.Domain.Usuario", "Anunciante")
                        .WithMany()
                        .HasForeignKey("AnuncianteId");

                    b.HasOne("EzDeal.Domain.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId");
                });

            modelBuilder.Entity("EzDeal.Domain.Reseña", b =>
                {
                    b.HasOne("EzDeal.Domain.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("AnuncioId");

                    b.HasOne("EzDeal.Domain.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("EzDeal.Domain.Solicitud", b =>
                {
                    b.HasOne("EzDeal.Domain.Anuncio", "Anuncio")
                        .WithMany()
                        .HasForeignKey("AnuncioId");

                    b.HasOne("EzDeal.Domain.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });
#pragma warning restore 612, 618
        }
    }
}
